config/routes.rb
Rails.application.routes.draw do



	get '/top' => 'root#top'

	devise_for :users

	root'root#top'

	resources :users, only: [:show, :index, :edit, :create, :update]
	resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user

	validates :title, presence: true,
					 length: { maximum: 20}


	validates :opinion, presence: true,
	 					length: { maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         attachment :image
         has_many :posts

        validates :name,  presence: true,
        				  length: { minimum: 2,maximum: 20}


        validates :itroduction, length: { maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    top_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
     devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!
 before_action :post_up_edit ,only:[:edit]

  def post_up_edit
  	@post = Post.find(params[:id])
  	if @post.user != current_user
		redirect_to posts_path
  	end
  end


def show
	@post_new = Post.new
	@post = Post.find(params[:id])
	@user = @post.user
end

def index
	@post = Post.new
	@user = User.find(current_user.id)
	@posts = Post.all

end

def create
	@post = Post.new(post_params)
	@post.user_id = current_user.id
	if @post.save
		flash[:notice] = "successfully"
		redirect_to post_path(@post.id)
	else
		@user=current_user
		@posts=Post.all
		@users=User.all
		render 'posts/index'
	end
end

def edit
	@post = Post.find(params[:id])
end

def update
	@post = Post.find(params[:id])
	@post.update(post_params)
	flash[:notice] = "successfully"
	redirect_to post_path(@post.id)
end

def destroy
	post = Post.find(params[:id])
	post.destroy
	redirect_to posts_path
end

private
    def post_params
        params.require(:post).permit(:title, :opinion)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def top
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user! 
  before_action :current_u ,only:[:edit]

  def current_u
  	@user = User.find(params[:id])
  	if @user != current_user
		redirect_to edit_user_path(current_user.id)
  	end
  end


	def show
		@post = Post.new
		@user = User.find(params[:id])
		@posts = @user.posts
	end

	def index
		@post = Post.new
		@user = User.find(current_user.id)
		@users = User.all
	end

	def edit
		@user = User.find(params[:id])
	end


	def update
		 	@user = User.find(params[:id])
		if	@user.update(user_params)
			flash[:notice] = "successfully"
			redirect_to user_path(@user.id)
		else
			render :edit
		end
	end


private
	def user_params
		params.require(:user).permit(:name,:image,:itroduction)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
    <%- flash.each do |name, msg| -%>
    <div class="message"><%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %></div>
  <%- end -%>

  
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav class="nav navbar-nav navbar-left">
            <span>Bookers</span>
        </nav>
        
        <nav>
         <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="glyphicon glyphicon-home" aria-hidden="true">
              <%= link_to 'Home', user_path(current_user.id), class: "home" %>
            </li>

            <li class="glyphicon glyphicon-user" aria-hidden="true">
              <%= link_to "Users", users_path, class: "users" %>
            </li>

            <li class="glyphicon glyphicon-book" aria-hidden="true">
              <%= link_to"Books", posts_path, class: "books" %>
            </li>

            <li class="glyphicon glyphicon-log-in" aria-hidden="true">
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: "logout" %>
            </li>


          <% else %>
            <li class="glyphicon glyphicon-home" aria-hidden="true">
              <%= link_to "Home",top_path, class: "home" %>
            </li>

            <li class="about glyphicon glyphicon-user" aria-hidden="true">
              <%= link_to "About",class: "about" %>
            </li>
            <li class="glyphicon glyphicon-edit" aria-hidden="true">
              <%= link_to "sign up", new_user_registration_path, class: "sign_up" %>
            </li>
            <li class="glyphicon glyphicon-log-in" aria-hidden="true">
              <%= link_to "login", new_user_session_path, class: "sign_in" %>
            </li>
          <% end %>
         </ul>
        </nav>
      </div>
  </header>
<%= yield %>

    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<!-- Post -->

<div class="body container">
	<div class="row">
		<div class="col-lg-4"></div>
		<div class="col-lg-4">

			<h1>Editing Book</h1>

			<%= form_for(@post) do |f| %>
			<tr>
				<td><h3>Title</h3></td>
			</tr>
			<tr>
				<td><%= f.text_area :title ,class: "book_title" %></td>
			</tr>
			<tr>
				<td><h3>Opinion</h3></td>
			</tr>
				<td><%= f.text_area :opinion ,class: "book_body"%><br></td>
			</tr>
			<tr>
				<td><%= f.submit'Update Book',class: "CreateBook label-primary" %></td>
			</tr>
			<% end %>

			<%= link_to"show",post_path(@post),class: "book_#{@post.id}"%>
			<%= link_to"Back",posts_path(@posts),class: "back"%>
		</div>
		<div class="col-lg-4"></div>
	</div>
</div>

app/views/posts/index.html.erb
<!-- Post一覧 -->


<div class="body container">
	<div class="row">
		<div class="col-lg-4">
			<% if @post.errors.any? %>
			  <div id="error_explanation" class="alert alert-danger">
			    <ul>
			      <% @post.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			    </ul>
			  </div>
			<% end %>


		<%= render 'users/list',post: @post, user: @user %>
		</div>

		<div class="col-lg-8">
			<table class="table">
			<h1>Books</h1>
			  <tr>
			  	<th></th>
				<th>Title</th>
				<th>Opinion</th>
			  </tr>

				<% @posts.each do |post| %>
					<tr>
						<td>
							<%= link_to user_path(post.user.id),class: "user_#{post.user.id}" do%>
							<%= attachment_image_tag post.user, :image ,:fill,50,50,format:'jpg',fallback: "noimage.jpg" %>
							<% end %>
						</td>
						<td>
							<%= link_to post.title, post_path(post.id),class: "book_#{post.id}" %>
						</td>
						<td>
							<%= post.opinion %>
						</td>
					</tr>
			<% end %>
			</table>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<!-- 投稿詳細 -->
<div class="body container">
	<div class="row">
		<div class="col-lg-4">
			<%= render 'users/list',post: @post_new, user: @user %>
		</div>

		<div class="col-lg-8">
			<table class="table">
			<h1>Book detail</h1>
					<tr>
						<td><%= attachment_image_tag @user, :image ,:fill,50,50,format:'jpg',fallback: "noimage.jpg" %><br>

						<%= link_to user_path(@user)do %>
						<div class= "user_#{user.id}"><%= @user.name %></div>
						<% end %>
						</td>

						<td><%= link_to post_path(@post)do %>
							<div class= "book_#{post.id}"><%= @post.title %></div>
							<% end %>
						</td>

						<td><%= @post.opinion %></td>

						<% if current_user.id == @user.id %>
						<td><%= link_to "Edit",edit_post_path(@post),class: "edit_book_#{@post.id} label label-success label-default"%></td>
						<td><%= link_to "Destroy",post_path,method: :delete, data: { confirm: '削除しますか？' } ,class: "destroy_book_#{@post.id} label label-danger label-default" %></td>
						<% end %>
					</tr>
			</table>
		</div>
	</div>
</div>

app/views/root/top.html.erb
<div class ="container">
	<div class= "row">
		<div class= "col-lg-4"></div>
		<div class= "col-lg-4">
			<p>Signed out successfully.</p>
			<h1>Welcom to Bookers !!</h1>
			<p>in Bookers,</p>
			<p>you can share and exchange your opinions,inpressions,and emotions<br>
			about varioius books!</p>

				<%= link_to "Log in", new_user_session_path, class: "sign_in btn btn-default label-info btn-lg btn-block" %>

				<%= link_to "Sign up",new_user_registration_path,class: "sign_up btn btn-default label-success btn-lg btn-block" %>

		</div>
		<div class= "col-lg-4"></div>
	</div>
</div>

app/views/users/_list.html.erb
		<div class="container">
			<div class="row">
				<div class="col-lg-4">

					<h1>User info</h1>
						<%= attachment_image_tag user, :image, :fill,100,100,format:'jpg',fallback: "noimage.jpg" %><br>
				<table class="table table-striped">
					<tr>
						<td>
							<h3>name</h3>
						</td>
						<td>
							<h3><%= user.name %></h3>
						</td>
					</tr>

					<tr>
						<td>
							<h3>introduction</h3>
						</td>
						<td>
							<%= @user.itroduction %>
						</td>
					</tr>
				</table>

				<% if current_user.id == @user.id %>
						<p><%= link_to "",edit_user_path(user),class: "edit_user_#{user.id} glyphicon glyphicon-wrench btn btn-default btn-block"%></p>
				<% end %>

					<h1>New book</h1>


					<%= form_for(post) do |f| %>

						<h4>Title</h4>
						<%= f.text_field :title, class: "book_title btn-block" %>

						<h4>Opinion</h4>
						<%= f.text_area :opinion, class: "book_body btn-block" %><br>

						<div>
						<%= f.submit'Create Book',class: "CreateBook label-primary btn-block" %>
						</div>
					<% end %>
				</div>
				<div class="col-lg-8"></div>
			</div>
		</div>
			

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>

<% if @user.errors.any? %>
	<div id="error_explanation" class="alert alert-danger">
		<ul>
			<% @user.errors.full_messages.each do |message| %>
			    <li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %> 

<h1>User info</h1>

<h4>Name</h4>
<%= f.text_field :name,class: "name" %>

<h4>image</h4>
 <%= f.attachment_field :image, class: "user_image" %>

<h4>Introduction</h4>
<%= f.text_area :itroduction, class: "introduction" %>

<%= f.submit'Update User' %>
<% end %>

app/views/users/index.html.erb
<!-- User一覧 -->
<div class="body container">
	<div class="row">
		<div class="col-lg-4">
			<%= render 'users/list',post: @post, user: @user %>
		</div>


		<div class="col-lg-8">
			<table class="table table-striped">
				<h1>Users</h1>
				 <tr>
				 	<th>image</th>
				 	<th>name</th>
				 	<th></th>
				 </tr>
				<% @users.each do |user| %>	　
					<tr>
					<td><%= attachment_image_tag user, :image ,:fill,50,50,format:'jpg',fallback: "noimage.jpg" %></td>
					<td><%= user.name %></td>
					<td><%= link_to "show", user_path(user.id), class: "user_#{@user.id}" %></td>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<!-- User詳細 -->
<% if flash[:notice] %>
<% end %>

<div class= "body container">
	<div class= "row">
		<div class="col-lg-4">
			<%= render 'users/list',post: @post, user: @user %>
		</div>

		<div class="col-lg-8">
			<table class="table table-striped">
			<h1>Books</h1>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opinion</th>
			</tr>
			<% @posts.each do |post| %>
				<tr>
				 <td><%= attachment_image_tag post.user, :image ,:fill,50,50,format:'jpg',fallback: "noimage.jpg" %></td>

				 <td><%= link_to post.title, post_path(post.id),class: "book_#{post.id}" %></td>

				 <td><%= post.opinion %></td>
				</tr>

			<% end %>
			</table>
		</div>
	</div>
</div>